### ISSUE TITLE
Can't use / */

### ISSUE THREAD

**Issue by wryun** [textX/textX#206]
```
from textx.metamodel import metamodel_from_str

mm = metamodel_from_str('''
Word: ('bar' / */)*;
''', skipws=False, debug=True)

print(mm.model_from_str('''bar bar''', debug=True))
```
Leads to:

```
...
  File "/usr/lib/python3.7/sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))
re.error: nothing to repeat at position 0
```

Presumably the space is getting stripped... it works if one adds a `(?i)` to the regex or uses the character class `[ ]`.

**Comment by igordejanovic** [comment]
Initial discussion [at SO](https://stackoverflow.com/questions/57944531/how-do-you-correctly-mix-textx-skipws-non-skipws)

**Comment by goto40** [comment]
Thank you for the investigation and the report. It seems to be a bug to me.

The reason is that leading and trailing white spaces are ignored in regular expressions. The fix is quite straight forward - however it has an minimal influence on existing code relying on the "feature" of ignoring the leading/trailing white spaces. 

We discuss this in #208.

**Comment by goto40** [comment]
The current master should fix this issue. See CHANGELOG.md.
