### ISSUE TITLE
Passing parameters to a metamodel (while opening a model) 

### ISSUE THREAD

**Issue by goto40** [textX/textX#240]
While discussing #239 I realized that we may need a way to pass parameters to a metamodel (while loading a model). Such parameters could influence scope providers (searchpath options or recursive globbing) or model checkers (object processors checking certain rules).

The parameter capabilities should be queryable via the meta-model ('which parameters exist?'). With such, an appropriate command-line interface _and_ ide interface could be deduced.

We could also solve #239 with that. It allows to keep the metamodel stateless and to influence the meta-model behavior on a per-file basis. 

What do you think?

**Comment by igordejanovic** [comment]
So, adding optional set of kw parameters to `model_from_file/str` of the meta-model. I like the idea. It would make it a kinda symmetric to `metamodel_from_file/str` and could indeed make model loading more flexible.

Do we need capabilities querying on the meta-model? How the meta-model creator would define those and how we could utilize them in a generic way? What would be the use-case?

**Comment by goto40** [comment]
I'm not sure about possible concrete implementations.

But the use case is to provide 
 * a CLI for the parameters: e.g. `textx check --lang-arg1=value1 --root-path=$(pwd) myfile.lang` (with the language parameters `lang-arg1` and `root-path`)
 * a easy IDE integration (e.g. provide a dialog with the possible parameters)

Details to be discussed.
Querying could be a special function of the metamodel returning the description: The meta model designer will just set the description: e.g., `metamodel.set_parameter_descrition("paramname", "meaning")`

Everything should be light-weight. 
 * All parameters are strings? This makes it easier for an IDE/CLI integration...
 * Parameters like search-paths or root-path/project-path could have a special meaning for the IDE (by convention). 
 * If a parameter is not set, the metamodel can do whatever the language designer wants to do (e.g. use CWD).

**Comment by goto40** [comment]
Maybe @danixeee has some good ideas. Let's wait for his comments as well!

**Comment by danixeee** [comment]
This sounds like a good solution to me and it should be easy to integrate with language server.

When document (model) is opened in a VS Code, _textX-LS_ finds appropriate `LanguageDesc` based on _language id_ or _file extension_ and then instantiate metamodel with `lang_desc.metamodel()`, so it will be really straightforward to pass `project_root` or any additional arguments there.
In VS Code, all projects/models could be under the same _workspace root_, or under separated _workspace folders_ and I could pass that path wherever we decide to.

**Comment by goto40** [comment]
@igordejanovic : what do you think about the querying capabilities?

**Comment by igordejanovic** [comment]
This idea resonates better now but still trying to figure out how everything fits together. 

So we have:
- A language creator that defines parameters and their descriptions
- A language user that creates model but the parameters are defined outside e.g. by someone who loads to model, a CLI or textX-LS.
- Who is using parameter values? In the textX-LS problem #239 the parameter would be something used by the scoping/global repository code so something known to exists in advance, before the meta-model has been built.

What we are building here is a way to define a part of the language outside of the meta-model and textX grammar that would be populated outside of the model and with a life-time of a model loading.

The value I see here is to make parts of the language defined outside of the grammar parametric. For example, to have object processors (which are part of the language outside of the grammar) parameterized during model loading. So, the code that *uses* the value of the parameters should be implemented by the language creator (part of the language) and the *parameter values* are given by the user who is loading the model to alter some of the load-time language property. Do you agree?

Sounds good but I would suggest when implementing this approach to be sure that parameters always have a fallback values so that model can be loaded even if parameter value is not given.

**Comment by goto40** [comment]
I agree! The parameters can be compared to compiler flags of a C-compiler: the user who loads a model file can influence the model loading (for C: search path, warning level, defines).

**Comment by goto40** [comment]
Rough plan for a demo/proof of concept:
 * kwargs for `model_from_xxx`
 * define possible parameters in metamodel
 * store parameters in _tx_parameters of models

Open:
 * passing parameters to included models with differing metamodel
 * cli integration (click) 

What do you think? 

I could take some time next weekend/Friday to make a demo. @danixeee, if you prefer to do it, just tell me...

**Comment by igordejanovic** [comment]
Sounds good but for #239 I don't think that should be solved by this language defined parameters as the code that would use params values is is not the part of the language (the code is in the scope providers), thus this parameter should not be left for definition to the language creator but should always be there. So, we should have a set of parameters that are built-in and whose values can be specified and used during model loading without the requirement to be defined in language meta-model. The built-in params would also have a fallback value, as the rest of the parameters, so everything will be fully backward compatible.

**Comment by danixeee** [comment]
@goto40 @igordejanovic I have started some work related to this in https://github.com/textX/textX/pull/242. It is still in WIP, but please left comments, so I can now if I am going in the right direction.

**Comment by igordejanovic** [comment]
@danixeee If we are going [down the route suggested by @goto40](https://github.com/textX/textX/issues/240#issuecomment-613047124), and that sounds like a good approach to me, I think that instead of introducing another param that we need to pass around it is better to solve that in  a uniform manner so that future addition of new params is easy. 

Thus, we will have a `**model_kwargs` which will be passed around and the code would extract what is needed. Validation of model args could be performed by checking of build-in params and the params defined by the meta-model. 

Once we have this new `model_kwargs` checked and passed around it will be much easier as addition of a new param would be just adding the description to either built-in params (if the param is used by the core) or to a meta-model (if it is used by the language definition, e.g. obj. processors...). The values of these params would be kept on a model.

This will remove the clutter of the additional params to the model loading calls, we can even move some of the existing params to the above frame.

**Comment by goto40** [comment]
Step 1: add `model_kwargs` to be stored in _tx_model_kwargs
Step 2: Adapt scope provider(s)
Step 3: discuss/implement parameter definition/checking

**Comment by danixeee** [comment]
@igordejanovic @goto40 Thanks for the responses. I will left some comments in #243.

**Comment by igordejanovic** [comment]
Closed via #243
