### ISSUE TITLE
Incompatible with attrs frozen class

### ISSUE THREAD

**Issue by markusschmaus** [textX/textX#247]
I'm using attrs frozen classes to represent data with correct equal and hash semantics. Unfortunately these classes are incompatible with textX.

```python
import attr
from textx import metamodel_from_str

grammar = """
Point: x=INT ',' y=INT;
"""

@attr.s(frozen=True)
class Point:
    x = attr.ib()
    y = attr.ib()

point1 = Point(0, 0)
mm = metamodel_from_str(grammar, classes=[Point])
point2 = mm.model_from_str("0, 0")
```

This is also true for classes which use `__slots__`

```python
class Point:
    __slots__ = ['x', 'y']

    def __init__(self, x, y):
        self.x = x
        self.y = y
```

**Comment by markusschmaus** [comment]
I created an implementation which stores the attributes of user classes in a separate dictionary:

https://github.com/markusschmaus/textX/commit/3a9aca2eb6b4656fa5342990784c425e549f47f7

All tests that functional tests that succeed on my system for master also succeed on this branch (33 tests also fail for master) and I added a small test for a user class that uses `__slots__`.

**Comment by igordejanovic** [comment]
Thanks for reporting and working on it. Looks good so far. I wonder for the failing tests you are getting. All functional tests should pass for all supported Python versions. What version of Python are you using? How is your environment setup? Can you tell from the error reports you are getting what would be the reason?

Please register a WIP PR for your working branch, I think this issue is important and would like to get it merged once it is finished.

**Comment by igordejanovic** [comment]
@markusschmaus I'm confirming that all tests are passing on  my end with your changes.

**Comment by markusschmaus** [comment]
https://github.com/textX/textX/pull/248

Great to hear that everything is passing on your end, I think the problem was with finding files, probably because I'm in the wrong working directory.

**Comment by markusschmaus** [comment]
My original PR didn't fully address the issue, https://github.com/textX/textX/pull/249
