### ISSUE TITLE
able to split model to several files and use import

### ISSUE THREAD

**Issue by csitarichie** [textX/textX#31]
Is there any plan to make a built in support for import mechanism in model and have grammar support for it ?.

Right now I see only a way to define a simple grammar just for import statement. Use this grammar to parse the model (the compile context) than use the Abstract tree to to open the import files do it recursively till all includes resolve. Concatenate all the includes in to a single mega model and parse that one with the real grammar which ignores the import statement. 

Is there a better way it do do right now ?.

**Comment by igordejanovic** [comment]
I had some plans to provide something along this line but never came up with something I would be satisfied with. All ideas/suggestions are welcomed ;)

Your approach is one of the viable approaches. Other is to use import statement as part of the real grammar and recursively parse imported models and reference them from the  source model. In this approach you must implement your own reference resolving/linking with scoping rules that will take into account imports but you'll have to make your own resolving for more complex languages anyway as the builtin resolving uses global scope.

**Comment by csitarichie** [comment]
Your suggestion seems to be a more generic one. And it also in kind of prescribes of creating implicit "modules" with the import statement. And as fare as I understood your documentation I can create my own class to implement opening the included "module" and parse it. 
Can I than just add as children to the class will it be accessible by the outer parser which just created my class ? to able to use them as referees ?. `

**Comment by igordejanovic** [comment]
Yes, you can provide your own class for any of your textX rules. This class will be instantiated by textX instead of dynamically created one.

An easier approach, if you only need to change the content of the object and don't
need additional methods, is to use [processors](http://igordejanovic.net/textX/metamodel/#processors). This is a general support for defining arbitrary language semantics. Object processors are Python callables that will get called whenever a object of a particular class/rule is instantiated with the object passed in as a parameter. You can then do a validation on the object or alter it in any way (e.g. add new attributes).

For example if you have something like this in your grammar:

```
Import: 'import' filename=FileName;
```

Then you can create object processor:

```python
def import_processor(import_obj):
    import_obj.ref_model = metamodel.model_from_file(import_obj.filename)
```

Register this on metamodel as described in the docs.

This will be applied recursively as the used metamodel is always the same.

As a side note, you will probably want to iterate over all objects of a particular type regardless of the module they reside in. For this you can't use `children_of_type` as this call returns only contained children according to the metamodel/grammar. Instead, register [custom class](http://igordejanovic.net/textX/metamodel/#custom-classes) for your model root (place where imports live) and provide method for iteration that will take into account imports.

Something like this:

```
MyModel:
  imports+=Import
  myobjs+=MyObj
  ...
;
```

```python
class MyModel(object):
      def __init__(self, parent, imports, myobjs...):
          self.parent = parent
          self.imports = imports
          self.myobjs = myobjs
          ... 

      @property
      def all_myobjs(self):
          return itertools.chain(self.myobjs,
                                 (i.ref_model.all_myobjs for i in self.imports))
```

When you register this class on meta-model you will have access to `all_myobjs` iterator which you can use in your code generator/interpreter:

```python
for myobj in model.all_myobjs:
    ... do something
```

**Comment by igordejanovic** [comment]
This is resolved by recent @goto40 work (available on `master`). See http://www.igordejanovic.net/textX/multimetamodel/
