### ISSUE TITLE
Grammar: Unordered group with nonsequential sub-repetitions

### ISSUE THREAD

**Issue by jhrmnn** [textX/textX#39]
`Rule: ('a' 'b'* 'c')# ;` parses `c a`, `a c b c`, or `b b b a c`, but not `b c b b a`. Is there a way to express such a grammar?

**Comment by igordejanovic** [comment]
I'm not sure that I understand the pattern `b c b b a`. Do you mean that `b` can appear anywhere multiple times while `c` and `a` can appear only once?

**Comment by jhrmnn** [comment]
Exactly.

**Comment by igordejanovic** [comment]
I don't think that such a rule can be expressed at the syntax level. When you need some complex structural rule, make it more lax at the grammar level (to parse all valid cases but probably some invalid too) and than use [object processors](http://www.igordejanovic.net/textX/metamodel/#processors) to make further constraints.

In your case you can make a rule:
```
Rule: ('a' | 'b'* | 'c')+
```
This will match `b c b b a` but will also match `b c b b c a` or `b b b` which we want to prevent.
Register than object processor for `Rule` and do further checks in Python and throw error if the rule is violated. You have all the context information needed (like position of each matched element).
BTW, you will have to collect matched elements as your rule given here is just a match rule and as such will return a string if not instructed otherwise by match filter.

**Comment by jhrmnn** [comment]
Right, that makes sense. I'll give it a go. Thanks!
