### ISSUE TITLE
Feature request: One case where error reporting could be improved - newline character (\n)

### ISSUE THREAD

**Issue by stanislaw** [textX/textX#397]
Hello,

It is surprising but after my previous report on Oct 27, 2020, I have been a very happy user of textX, which makes it 2.5+ years by now 😄 

I would like to report something that I notice and think about from time to time, and then I postpone and postpone reporting it over and over again.

The line below shows both issues at the same time:

```
E           textx.exceptions.TextXSyntaxError: None:5:10: Expected Not or '.' or '
E           ' or '>>>' => ' COMMENT: *'
```

The newline symbol is printed as-is to the console, which makes it rather confusing even for me, who is not a beginner when it comes to working with DSLs based on textX. Would it be possible to replace `'\n'` with something like "line break" or "newline character", so that it is immediately clear that we are talking about the line break in this case?

The second question/report has been extracted to a separate issue, see https://github.com/textX/textX/issues/399.

I am curious to know if either or both of these features would be doable with not much effort. Thank you.

**Comment by goto40** [comment]
Hi.
Thank you very much for your nice feedback!

For the first part I think we could try changing [this code](https://github.com/textX/Arpeggio/blob/0a57265cf465d3a69ddaa1037c9726daedb4cf4f/arpeggio/__init__.py#L99): maybe just replacing all newlines with `\n`... With a proper test case (in Arpreggio *and* textx we sould be safe)...

@igordejanovic - what do you think? If you also think this is a simple thing, I could help you, @stanislaw, to prepare a PR (if you are interested). We are always looking for active coworkers!

For the second part - I did not check how to do it...

**Comment by stanislaw** [comment]
In addition to the feature request above, I very often find the "raw" regular expression suggestions very confusing to someone who is using my software without being familiar with the underlying grammar.

Consider this kind of report:

```
E           textx.exceptions.TextXSyntaxError: None:5:6: Expected Not or '\S' or '>>>' => 'ENT] UID: *  '
```

In this case, the `\S` part is reported because it is coming from the SingleLineString which is defined as follows:

```
SingleLineString:
  (!MultiLineStringStart /\S/) (!MultiLineStringStart /./)*
;
```

Would it make sense to provide annotations that could be used in the reporting instead of the regular expressions. Example:

```
SingleLineString[description="Single-line string. Must start with a non-empty character."]:
  (!MultiLineStringStart /\S/) (!MultiLineStringStart /./)*
;
```

```
E           textx.exceptions.TextXSyntaxError: None:5:6: Expected Not or SingleLineString or '>>>' => 'ENT] UID: *  '
SingleLineString -> Single-line string. Must start with a non-empty character.
```

The definition of the actual interface is quite raw in my mind but you should get the idea.

**Comment by igordejanovic** [comment]
Hi, 
@stanislaw thanks for the nice feedback. It is always great to hear that textX is useful to someone out there. :)

@goto40 I agree with you. Replacing literal newlines should be simple enough. For the `Not` part I don't like the current output also but IIRC it's a bit tricky but definitely worth checking out. 

@stanislaw `description` feature is nice, it would definitely improve error messages. I haven't checked how big of a change it would be but a first guess is that we should probably need to keep the last description while descending down the PEG rules. The tricky part is to decide when to use the description on `NoMatch`. If the last description is to high in the call stack it could be misleading. One approach could be to use descriptions only on match rules, which is probably a good first approximation.

@stanislaw Since this `description` idea is a separate feature, and not a small one, could you please create a new issue with the idea from your comment above so that we can track it easier.
