### ISSUE TITLE
comment makes fail the correct language parsing

### ISSUE THREAD

**Issue by deeagle001** [textX/textX#53]
I have the following model, which is sensitive to comment existence.
Whenever a comment exists, the parse fails to return the correct AST.

# Symptom 1

The model is the following:
```
file:
    lines*=cascading
;

Comment:
    /#.*$/
;

space[noskipws]:
    /[ \t]*/
;

cascading:
    group | line
;

line[noskipws]:
   /\s*/-
   (modifier=ID space &ID)? keyword=ID 
   /\s*/-
;

group:
    keyword=ID '{' entries*=cascading '}'
;
```

I would like to parse a file like this.
```
group
{
    ZERO
    ONE
    TWO
}
```

What I expect, that all the capitalized word here catch as `keyword`.
Which is working well.

But, if I make a comment after the `ZERO` like this,
```
...
   ZERO # comment
...
```
the behavior changes totally, and the `ZERO` will be a `modifier` for `ONE`.
This is what I declared as bug as the first part.

# Symptom 2

If I change the model, to remove the `keyword` from the `group` like this:
```
group:
    '{' entries*=cascading '}'
;
``` 
and remove the corresponding group keywords from the file like this:
```
{
    ZERO # comment
    ONE
    TWO
}
```
, the bug disappears, and work flawlessly even with comments.

That means, that somehow the `group` language element effects the parsing of the `line`, which is also weird.

### Hint:
I checked the debug output of these solutions for commented input.
Whenever the fault happened, the textX do not try to parse the comment just jumped over it instead.

**Comment by igordejanovic** [comment]
There was an error in Arpeggio in the comment parsing optimization. Namely, in parsing `cascading` rule `group` rule is tried first. That rule consumes all whitespaces as there is no `noskipws`. When `line` rule gets its turn parser sees only `ZERO ONE`, i.e. no comment in between. This is now fixed on Arpeggio master branch. Please use Arpeggio from `master`.

**Comment by deeagle001** [comment]
Thank you. I do appreciate your fast and great work.

Do you have any plan already, when to release this fix in Arpeggio and make it available via pip?

**Comment by igordejanovic** [comment]
I've just publish a bugfix release. Let me know is it works for you.

**Comment by deeagle001** [comment]
Hello.

I tried out, and it is almost good. :)
Fixes the actual problem, but losing regression.

Now, if I place a comment after curly brackets, the text throws TextXSyntaxError.
Like this:
```
group
{  # this throws error
    ZERO
    ONE
    TWO
} # this also throws error
```

**Comment by igordejanovic** [comment]
Things get really tricky when `noskipws` explicit whitespace handling  is combined with implicit comments parsing.

What happens here is that `Line` rule starts with collecting whitespaces but comment match will happen before each other match, thus, you will have comment match (will not succeed), whitespace match (will succeed), comment match (will succeed), and than parser will try to match the next rule which is `ID` and that doesn't succeeds because there is whitespaces after previously matched comment.

To remedy this problem you can match whitespaces twice:
```
    line[noskipws]:
    /\s*/ /\s*/
    (modifier=ID space &ID)? keyword=ID
    /\s*/ /\s*/
    ;
``` 
BTW, no need to use suppression on whitespace matching as the rule is not Match rule. If you follow the order in which match will happen you can see that whitespaces before and after the comment will be collected. But, than again what if there is few lines of comments? You could use `/\s*/*`.

The error reported at the end is also due to interleave between `noskipws` and `skipws` rules and the way PEG parser works. PEG tries matches from left to right. In your `cascade` rule you try `group` first and than `line`. First rule skips whitespaces, while the other doesn't. Parser will try `group` at the end first and consume all whitespaces and the comment, but that match will not succeed and will be back-tracked. After that `line` rule will try to match at the same location but since this rule is `noskipws` and it doesn't succeed either it will leave parser right after the `}`. The workaround for this is to add another whitespace match at the very end.

```
    file:
        lines*=cascading /\s*/
    ;
```
This will consume whitespaces at the end and the parser will be able to parse/skip the comment and reach EOF.

**Comment by igordejanovic** [comment]
Although, I think the last problem, with comments at the end, could be supported in the parser without much trouble. If multiple rules are tried at the end and if any of those rules (no matter what's their order) consume whitespaces (and comments) that parse should be accepted. I'll check on this idea.

**Comment by deeagle001** [comment]
Thank you for the suggestions.

I tried the `/\s*/*` approach, and it seems okay. I had to add one additional `/\s*/` after `lines` collecting rule you mentioned, and now I am unable to break it with any strange comments in the input and seems pretty stable.
The metamodel looks quite ugly with this decorations. [But that's a sacrifice I willing to make.](https://memegenerator.net/instance/66563438/lord-farquaad-some-of-you-may-die-some-of-you-may-die-but-thats-a-sacrifice-im-willing-to-make)
So it works like charm.

Even though I reached the point I wanted, the original problem still present.
**The existence of comments shall not affect the result of parsing!**
This is my opinion, but you can freely disagree.

**Comment by igordejanovic** [comment]
Glad it works for you.

> The existence of comments shall not affect the result of parsing!

I understand your point but it's not that easy. The result of the parsing should be in accordance to the grammar and the parser interpretation of the grammar and its built-in rules. It would be the same as stating that the existence of whitespaces should not affect the result of parsing. Sure, but only if we handle those whitespaces either explicitly or implicitly.

When you are using the default mechanism for whitespace/comment skipping but are taking over parts of the parse to handle whitespaces yourself then you should take an extra step to ensure proper parsing in the context of comments. 

Probably the core of the problem is treating comments differently than whitespaces by textX/Arpeggio. We could argue whether comments are or aren't the same as whitespaces. Actually, I'm leaning more towards treating them the same as whitespaces. In that way using `noskipws` would mean *don't skip whitespaces **and** comments*. That would probably be more consistent and prevent gotchas like this. Although, your grammar `noskipws` rule would need to include explicit matching of comments on all places you would like to allow them which might be ok if there aren't many `noskipws` rules. Not sure if this would be the right approach though.

I would leave this issue open until I support comment at the end of file in case of having at least one rule with `skipws` enabled that tried to match at the end.

I'm also registering a new issue/poll to gather feedback from the community about this *treating comment as whitespace* issue.

**Comment by deeagle001** [comment]
I found an additional issue, which is related to the solution/workaround you provided.

Maybe with your fix as well in Arpeggio 1.7.1.

`_tx_position` returns bad position for AST element. It merges the lines.
Yield line and column would be correct if the lines in the `noskipws` rule were merged together.

So the position not refers to the actual model input, but for some kind of prepared model, which is not visible to the user, and it is much harder to find the real problem.

I assume, that the `/\s*/` insertions to my metamodel cause this.

If you need, I can create a separate issue for that.
(This was easier, and this way it has a history which can help better understand the problem.)

**Comment by igordejanovic** [comment]
Thanks for the report. Yeah, separate issue that links to this one would be better for tracking.
Could you please provide a small test example that manifest the bug?

**Comment by deeagle001** [comment]
During writing the issue description, I figured out it was my fault.
I failed to put `-` sign after `/\s*/`, which caused, that the preceding whitespaces including line breaks were part of the rule match.

Sorry for that!

Now everything works fine.
