### ISSUE TITLE
obj_processors not working without full assignment chain

### ISSUE THREAD

**Issue by approxit** [textX/textX#88]
**Textx version:**
```
1.7.1
```

**Python version:**
```
3.6.5
```

**Minimal example:**
```python
import textx

mm = textx.metamodel_from_str('''
    Model:
      'begin' some_value=MyFloat some_other_value=Collection 'end'
    ;
    
    Collection:
        MyFloat
    ;
    
    MyFloat:
      /\d+\.(\d+)?/
    ;
''')
mm.register_obj_processors({
    'MyFloat': lambda x: float(x)
})

m = mm.model_from_str('''
    begin
        1.0
        2.0
    end
''')

print('Some value repr:', repr(m.some_value))
print('Some other value repr:', repr(m.some_other_value))
```
**Expected results:**
```
Some value repr: 1.0
Some other value repr: 2.0
```

**Actual Results:**
```
Some value repr: 1.0
Some other value repr: '2.0'
```

**Problem:**
As example shows, `obj_processors` is not called when there is no direct assignment chain. Of course `Collection` in real life would contain more syntax, but its make no difference in this case. Need for `Collection` is required since in assignments we can use only regexes or single rule.

Sadly this case makes `obj_processors` quite unusable. 😢

**Comment by igordejanovic** [comment]
Hi @approxit. Thanks for the report.

I don't think this to be a bug. It should be the expected behavior. The reasoning behind is that `Collection` is recognized as a [match rule](http://www.igordejanovic.net/textX/latest/grammar/#rule-types) so it shall return string unless explicitly converted by obj. processor. So, to achieve desired behavior you should register the same object processor for both `MyFloat` **and** `Collection` in your case. Making an assignment in `Collection` rule would change the type of rule to `common rule` which would make referenced rules objects to propagate up.

As a side note, there are some fixes in the way object processors are called in the development version but it seems that it doesn't influence the behavior in this example.

**Comment by approxit** [comment]
You're right. `Collection` represented as single rule is handled as match rule (because with all referenced subrules are match rules - as docs points). So `2.0` fragment could be moved up to the `Collection` rule, which is not in `obj_processors`. Cleanly not working.

Lets change `Collection` rule type then.

```python
import textx

mm = textx.metamodel_from_str('''
    Model:
      'begin' some_value=MyFloat some_other_value=Collection 'end'
    ;

    Collection:
        MyAnotherCollection | MyFoo
    ;

    MyAnotherCollection:
        value=MyFloat
    ;

    MyFloat:
      /\d+\.(\d+)?/
    ;

    MyFoo:
        foo="bar"
    ;
''')
mm.register_obj_processors({
    'MyFloat': lambda x: float(x)
})

m = mm.model_from_str('''
    begin
        1.0
        2.0
    end
''')

print('Some value repr:', repr(m.some_value))  # returns Some value repr: 1.0
print('Some other value repr:', repr(m.some_other_value.value))  # return Some other value repr: '2.0'

```

Now, referring to docs, `Collection` should be an abstract rule, which should be transparent in behaviour. All `Collection` children are common rules too. But, still `obj_processors` is not working.

Super confusing for me actually, but if we change `MyFloat` to object BAM it works!

```python
import textx

mm = textx.metamodel_from_str('''
    Model:
      'begin' some_value=MyFloat some_other_value=Collection 'end'
    ;

    Collection:
        MyFloat
    ;

    MyFloat:
      value=/\d+\.(\d+)?/
    ;
''')
mm.register_obj_processors({
    'MyFloat': lambda x: float(x.value)
})

m = mm.model_from_str('''
    begin
        1.0
        2.0
    end
''')

print('Some value repr:', repr(m.some_value))  # returns Some value repr: 1.0
print('Some other value repr:', repr(m.some_other_value))  # return Some other value repr: 2.0
```

What I'm missing right now?

**Comment by igordejanovic** [comment]
Yup, you are right but the problem seems to be resolved by @goto40 in PR #79, at least your first example in the previous comment works for me with `master` version. Could you verify?

This fix, together with some other improvements in multi-meta-model support will arrive with 1.8.0 version which should be released soon. For the time being, please use `master` version.

**Comment by igordejanovic** [comment]
Version 1.8.0 is released on PyPI. Please check if it solves the problem and feel free to close this issue if it does or comment further if you still experience problems.

**Comment by approxit** [comment]
1.8.0 fixes the problem!

@igordejanovic, @goto40
Thanks for fast feedback and your work, guys!
