### ISSUE TITLE
Breaking API changes

### ISSUE THREAD

**Issue by ghost** [textX/textX#89]
It seems that in version 1.7.0 there are changes breaking the compatibility with the previous version (certtools/intelmq#1246).

The specific error that we get is:
> AttributeError: module 'textx.model' has no attribute 'metamodel'

Maybe `textx.model.metamodel()` is now `textx.model.get_metamodel()`

And then
> AttributeError: 'TextXModelParser' object has no attribute 'line_ends'

(and probably more)

Is there a stable API which can be used? Is there a list of removed methods with their corresponding replacements?

**Comment by igordejanovic** [comment]
Hi @wagner-certat. Thanks for the report.

We are trying to keep API as much stable as possible but backward compatibilities creep in occasionally which should be noted in changelog. If not, that is a bug. Version 1.7.0 was a release with a lot of changes so we might miss to list some in the changelog. BTW, there is a bugfix release 1.7.1 so I suggest you to go for that version although I don't think that would solve this issue.

We decided recently to apply semantic versioning and increase major version number at each breaking change so that should better communicate changes severity.

Could you provide more info about the error your are experiencing? At least exact Arpeggio version and the full stack trace of the error. Also if you could outline the general usage pattern, that would also be helpful in tracing down the problem.

**Comment by igordejanovic** [comment]
There are breaking API changes from issue #48 that seems not registered in the changelog. Will fix it. That is the first part of the problem. But for the second would need more input.

**Comment by ghost** [comment]
> BTW, there is a bugfix release 1.7.1 so I suggest you to go for that version although I don't think that would solve this issue.

I re-tested it with the current 1.8.0 release, but it was also a problem with 1.7.1.

> We decided recently to apply semantic versioning and increase major version number at each breaking change so that should better communicate changes severity.

Great to hear :)

> Could you provide more info about the error your are experiencing? At least exact Arpeggio version and the full stack trace of the error. Also if you could outline the general usage pattern, that would also be helpful in tracing down the problem.

The Arpeggio version is the recent one, 1.9.0.

The (relevant part of the) traceback from the linked issue:
```
  File "/home/travis/build/certtools/intelmq/intelmq/bots/experts/sieve/expert.py", line 323, in get_linecol
    metamodel = textx.model.metamodel(model_obj)
AttributeError: module 'textx.model' has no attribute 'metamodel'
```
With this code we want to get the position of a rule in the model.

Our full code is here: https://github.com/certtools/intelmq/blob/maintenance/intelmq/bots/experts/sieve/expert.py

**Comment by ghost** [comment]
Using
```
metamodel = textx.model.get_metamodel(model_obj)
tup = metamodel._parser.pos_to_linecol(model_obj._tx_position)
```
gives
```
  File "/home/sebastian/dev/intelmq/intelmq/bots/experts/sieve/expert.py", line 326, in get_linecol
    tup = metamodel._parser.pos_to_linecol(model_obj._tx_position)
  File "/home/sebastian/dev/intelmq/intelmq/venv/lib/python3.6/site-packages/arpeggio/__init__.py", line 1616, in pos_to_linecol
    if not self.line_ends:
AttributeError: 'TextXModelParser' object has no attribute 'line_ends'
```

**Comment by goto40** [comment]
I am pretty sure I spotted the problem: for multi
file models we had to instantiate one parser per model. The parser of the
meta model is only a blue print.

You need to 

 * use "model_obj._tx_parser" 
 * instead of the "metamodel._parser"

See #93 for more clarification.
See also http://www.igordejanovic.net/textX/stable/metamodel/

"""
When parsing a model file or string a new parser is cloned for each model.
This parser can be accessed via the model attribute _tx_parser.
"""

Maybe check this out and give us feedback if the problem is solved. 

Best, Pierre

**Comment by ghost** [comment]
Getting the parser with `parser = model_obj._tx_metamodel._parser` and calling `parser.pos_to_linecol(model_obj._tx_position)` gives me:
```
  File "/home/sebastian/dev/intelmq/intelmq/bots/experts/sieve/expert.py", line 326, in get_linecol
    tup = parser.pos_to_linecol(model_obj._tx_position)
  File "/home/sebastian/dev/intelmq/intelmq/venv/lib/python3.6/site-packages/arpeggio/__init__.py", line 1616, in pos_to_linecol
    if not self.line_ends:
```
That's the same error that @antoinet faced when debugging this issue.

BTW:
I may seem like I am reaching out for help to fix our own code. While this is partly true, I hope that the backwards compatibility and docs can be improved with this procedure.

**Comment by igordejanovic** [comment]
What @goto40 suggested it to access the parser via the model object, not metamodel. Try `parser = model_obj._tx_parser`. The parser on the metamodel is just a prototypical instance used to create new model parsers. That's why it lacks `line_ends`.

> BTW:
> I may seem like I am reaching out for help to fix our own code. While this is partly true, I hope that the backwards compatibility and docs can be improved with this procedure.

No problem. Thanks for reporting. There was indeed missing pieces of information in the changelog.

**Comment by ghost** [comment]
> What @goto40 suggested it to access the parser via the model object, not metamodel. Try `parser = model_obj._tx_parser`.

Then I get
```
    parser = model_obj._tx_parser
AttributeError: 'IfClause' object has no attribute '_tx_parser'
```

> No problem. Thanks for reporting. There was indeed missing pieces of information in the changelog.

Yeah, I have seen you added the `.metamodel` -> `.get_metamodel` change here 3fcfc9efc68687d49d8026eb9e3f3d438ee81171

**Comment by goto40** [comment]
Hello,

Is your model_obj a model or a object inside a model? It seems to me, from your code, that it is an arbitrary object in the model.

Then you need to use: get_model(model_obj)._tx_parser

I am sorry for this inconvenience...

**Comment by ghost** [comment]
Thanks! The final solution is now:

* post 1.7.0:
`parser = textx.model.get_model(model_obj)._tx_parser`
* pre 1.7.0:
`parser = textx.model.metamodel(model_obj).parser`
