### ISSUE TITLE
object_processors do not run on rule

### ISSUE THREAD

**Issue by Geniedesalpages** [textX/textX#96]
I have simplified my grammar to reproduce a bug in object processors:

```python
from textx import metamodel_from_str
grammar = """
Command:
    name=ID parameters=ParameterList
;
    
ParameterList:
    '(' parameters*=Parameter ')'
;
Parameter:
     ExplicitFloat
;
ExplicitFloat:
    /-?\d+\.\d+/
;
"""

code = """
mycommand(0.1 1.1)
"""
mm = metamodel_from_str(grammar)
mm.register_obj_processors({'ExplicitFloat': lambda x: float(x)})

mymodel = mm.model_from_str(code)

first_param = mymodel.parameters.parameters[0]
assert isinstance(first_param, float), f"first parameter is of type {type(first_param)} instead of float"
```

The ExplicitFloat is not changed to a float and remains str. If the ExplicitFloat appears "higher" in the syntax tree of the grammar, then it occasionally translates it. Am I doing something wrong, or is there a bug in the object processors?

**Comment by goto40** [comment]
Thank you for your investigation. I think you need to assign the explicit float object to an attribute, e.g., value=ExplicitFloat.

With this change, your program works for me:

 * Grammar change: Parameter: value=ExplicitFloat
 * assert change: assert isinstance(first_param.value, float), f"first parameter is of type {type(first_param)} instead of float"

Note, that we had some issues with object processors. You should update in any case to textX 1.8

**Comment by goto40** [comment]
Note: The rule Parameter is a match rule in my eyes, as ExplicitFloat is... Thus, I assume, the nested match rule ExplicitFloat is not instantiated... 

A related unit test which may help as a workaround is https://github.com/igordejanovic/textX/blob/master/tests/functional/examples/test_modeling_float_int_variables.py.

**Comment by goto40** [comment]
We need to clarify how object processors apply to match rules, especially for nested match rules.

**Comment by Geniedesalpages** [comment]
Thank you for your quick reply!

By changing it to have value=ExplicitFloat in the grammar, i managed to run the above example. In my original grammar (which is more nested and has more intermediate steps) this approach works in some cases but not in others, I couldn't pin down the error as of yet (I am using 1.8.0 for reference).

Is the object processor not applied right after the instantiation of the Rule, independent of where it is in the AST?

My `Parameter` rule in the full grammar actually looks like this:

```
Parameter:
     (NullValue | ExplicitFloat | ExplicitInt | ID | RUNID  | STRING | NamedVariable) !'='
;
```
where all of these rules are terminals. Maybe that gives some insight?

**Comment by igordejanovic** [comment]
In my view this is expected behavior, but maybe a docs need more clarification. There are [three types of rules](http://www.igordejanovic.net/textX/stable/grammar/#rule-types). Match rules always produce a string unless explicitly processed by obj. processor. In this case (as @goto correctly observed)  `Parameter` is a match type rule so it will produce a string unless there is obj. processor for it. I think that current implementation won't even follow the referenced match rules and execute referenced rules obj. processors. Only the first level of match rule object processors are executed as there is no point going further if we agree that match rules return strings (i.e. obj processor for match rule *always* gets a string and produce some other object out of it, it shouldn't handle other types of objects, like a float in this case).

A proper way to handle this is by using assignment at the `Parameter` level as @goto40 suggested which turns `Parameter` to a common rule and thus obj. processor for `ExplicitFloat` is properly called.

If you find a situation in your grammar where this is not the case please report.

We could of course discuss whether match rules should be handled differently.

**Comment by igordejanovic** [comment]
Seems that I managed to reproduce a problem with obj. processor calling for match rules.

In this example:

```python
from textx import metamodel_from_str
grammar = """
Command:
    name=ID parameters=ParameterList
;

ParameterList:
    '(' parameters*=Parameter ')'
;

Parameter:
     value=ExplicitFloat | value=INT
;

ExplicitFloat:
    /-?\d+\.\d+/
;
"""

code = """
mycommand(0.1 1)
"""
mm = metamodel_from_str(grammar)

mm.register_obj_processors({
    'Parameter': lambda x: x.value,
    'ExplicitFloat': lambda x: float(x)})

mymodel = mm.model_from_str(code)

first_param = mymodel.parameters.parameters[0]

assert isinstance(first_param, float), f"first parameter is of type {type(first_param)} instead of float"
```

`Parameter` rule is a common rule and thus `ExplicitFloat` obj. processor should be called, but apparently with `1.8.0` it is not. Notice also the use of `Parameter` obj. processor which unpacks the `value` attribute if you want to have a nicer AST, i.e. you don't want for parameters to be full objects with `value` attribute.

**Comment by Geniedesalpages** [comment]
Thanks again for the detailed reply, `'Parameter': lambda x: x.value` is a nice idea!

What I find a bit unintuitive is that Parameter (without the value=..) does apparently not act as a fall-through, and hence wouldn't trigger the object processor, even when after bug-fixing the above? As far as I understand, it also only transforms strings to something else. Wouldn't it be more powerful if it could do more?

These are just some thoughts, I like textx a lot because of its straight-forwardness and superior grammar grammar compared to xtext

**Comment by igordejanovic** [comment]
Yup, I understand your way of thinking but if we do a fall-through than there would be a consistency problem as match obj. processor at higher hierarchy level could actually get a non-string objects.

Imagine this ill designed example:
```
Parameter:
   '+' ExplicitFloat;
```
This should match `+` sign and float afterwards, but what should be returned from this rule? And, what should eventual `Parameter` obj. processor get as it parameter? It is not easy to decide, and that's why a simple approach of not propagating obj. processor call in case of hierarchy of match rule is chosen. I get we just need a better docs on this and this issue above fixed.

**Comment by Geniedesalpages** [comment]
Ah ok i see the issue, that makes sense!

**Comment by goto40** [comment]
I am not so happy with replacing a rules' outcome with an object processor, when the inner values of the rule instance is also affected by an object processor:

	'Parameter': lambda x: x.value

The problem is, that the order of object processor execution needs to be specified for that (e.g., first transform the value inside "Parameter", then transform "Parameter").

**Comment by goto40** [comment]
I was not aware, that we can assign different types to an attribute (value in rule Parameter). Is the metaclass correctly assigned in that case? 

```
Parameter:
     value=ExplicitFloat | value=INT
;
```

**Comment by igordejanovic** [comment]
> The problem is, that the order of object processor execution needs to be specified for that (e.g., first transform the value inside "Parameter", then transform "Parameter").

It is perfectly safe for match rules as their obj. processors must finish before the assignment to the referencing attribute is done. As a side note I think the order should be predetermined for all "embedded" (non-referenced) objects as we need the contained objects to be already processed to be able to do processing on the current object (transform/replace etc.). The order should be bottom-up.

> I was not aware, that we can assign different types to an attribute (value in rule Parameter). Is the metaclass correctly assigned in that case?

Didn't check but IIRC if the type in the attribute multiple assignments differs the generic `OBJECT` will be set as the metaclass. In the future we could actually search for the common base type and set that instead.

**Comment by igordejanovic** [comment]
@Geniedesalpages This issue is now fixed on master. The calls to match rules are done on all levels. The inconsistency in nested rules [I mentioned before](https://github.com/textX/textX/issues/96#issuecomment-435680121) is fixed so that in case you have a nesting match rule with multiple parts (like `'+' ExplicitFloat`) everything will get converted to text and concatenated. Please see [this test](https://github.com/textX/textX/blob/master/tests/functional/test_processors.py#L252).

**Comment by Geniedesalpages** [comment]
Very cool, I will use it as soon as it's in a release! Is there another release planned before 2.0.0?

**Comment by igordejanovic** [comment]
I think not as the 2.0.0 should be released very soon.
